// enum для ключей
export const KeysCriticalValue = {
  Completed: 'completed',
  Schizoid: 'schizoid',
  Hysteroid: 'hysteroid',
  SelfDoubt: 'selfDoubt',
  Aggressive: 'aggressive',
  Hyperthymic: 'hyperthymic',
  DistrustOfPeople: 'distrustOfPeople',
  EmotionallyLabile: 'emotionallyLabile',
  FamilyRelationships: 'familyRelationships',
  BarriersBall: 'barriersBall',
  PessimismBall: 'pessimismBall',
  InsolvencyBall: 'insolvencyBall',
  MaximalismBall: 'maximalismBall',
  UniquenessBall: 'uniquenessBall',
  AffectivityBall: 'affectivityBall',
  PerspectiveBall: 'perspectiveBall',
  AntisuicidalBall: 'antisuicidalBall',
  DemonstrativenessBall: 'demonstrativenessBall',
  StudyBall: 'studyBall',
  DirectBall: 'directBall',
  ReverseBall: 'reverseBall',
  StudyGroupsBall: 'studyGroupsBall',
  IBall: 'iBall',
  VBall: 'vBall',
  IIBall: 'iiBall',
  IVBall: 'ivBall',
  VIBall: 'viBall',
  IIIBall: 'iiiBall',
  Mysticism: 'mysticism',
  Conformism: 'conformism',
  CultOfPower: 'cultOfPower',
  Intolerance: 'intolerance',
  ProtestActivity: 'protestActivity',
  SocialPessimism: 'socialPessimism',
  AntiIntraception: 'antiIntraception',
  NormativeNihilism: 'normativeNihilism',
  ConventionalCoercion: 'conventionalCoercion',
  DestructivenessAndCynicism: 'destructivenessAndCynicism',
  PermissibilityOfAggression: 'permissibilityOfAggression',
  SuggestibilityBall: 'suggestibilityBall',
  TotalBall: 'totalBall',
  EthnicBall: 'ethnicBall',
  SocialBall: 'socialBall',
  PersonalityBall: 'personalityBall',
  SearchOfThrill: 'searchOfThrill',
  DesireForDifficulties: 'desireForDifficulties',
  IntoleranceOfMonotony: 'intoleranceOfMonotony',
  SearchOfNewExperiences: 'searchOfNewExperiences',
  OrganizationComp: 'organizationComp',
  SocioCulturalComp: 'socioCulturalComp',
  SocioPracticalComp: 'socioPracticalComp',
  SocioActivityComp: 'socioActivityComp',
  OrientationComp: 'orientationComp',
}; // для completed — boolean, для остальных — массив условий

// затем объект с этими типами, пример
export const keysCriticalValue = {
  [KeysCriticalValue.Completed]: [{ operator: '=', value: false }],
  [KeysCriticalValue.Schizoid]: [{ operator: '>', value: 3 }],
  [KeysCriticalValue.Hysteroid]: [{ operator: '>', value: 3 }],
  [KeysCriticalValue.SelfDoubt]: [{ operator: '>', value: 7 }],
  [KeysCriticalValue.Aggressive]: [{ operator: '>', value: 5 }],
  [KeysCriticalValue.Hyperthymic]: [{ operator: '>', value: 3 }],
  [KeysCriticalValue.DistrustOfPeople]: [{ operator: '>', value: 6 }],
  [KeysCriticalValue.EmotionallyLabile]: [{ operator: '>', value: 3 }],
  [KeysCriticalValue.FamilyRelationships]: [{ operator: '>', value: 7 }],
  [KeysCriticalValue.BarriersBall]: [{ operator: '=', value: 6.9 }],
  [KeysCriticalValue.PessimismBall]: [{ operator: '=', value: 6 }],
  [KeysCriticalValue.InsolvencyBall]: [{ operator: '=', value: 7.5 }],
  [KeysCriticalValue.MaximalismBall]: [{ operator: '=', value: 6.4 }],
  [KeysCriticalValue.UniquenessBall]: [{ operator: '=', value: 0 }],
  [KeysCriticalValue.AffectivityBall]: [{ operator: '=', value: 6.6 }],
  [KeysCriticalValue.PerspectiveBall]: [{ operator: '=', value: 6.6 }],
  [KeysCriticalValue.AntisuicidalBall]: [{ operator: '=', value: 0 }],
  [KeysCriticalValue.DemonstrativenessBall]: [{ operator: '=', value: 6 }],
  [KeysCriticalValue.StudyBall]: [{ operator: '<', value: 8 }],
  [KeysCriticalValue.DirectBall]: [{ operator: '<', value: 8 }],
  [KeysCriticalValue.ReverseBall]: [{ operator: '>', value: 8 }],
  [KeysCriticalValue.StudyGroupsBall]: [{ operator: '<', value: 8 }],
  [KeysCriticalValue.IBall]: [{ operator: '<', value: 4 }],
  [KeysCriticalValue.VBall]: [{ operator: '<', value: 4 }],
  [KeysCriticalValue.IIBall]: [{ operator: '<', value: 4 }],
  [KeysCriticalValue.IVBall]: [{ operator: '<', value: 4 }],
  [KeysCriticalValue.VIBall]: [{ operator: '<', value: 4 }],
  [KeysCriticalValue.IIIBall]: [{ operator: '<', value: 4 }],
  [KeysCriticalValue.Mysticism]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.Conformism]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.CultOfPower]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.Intolerance]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.ProtestActivity]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.SocialPessimism]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.AntiIntraception]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.NormativeNihilism]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.ConventionalCoercion]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.DestructivenessAndCynicism]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.PermissibilityOfAggression]: [{ operator: '>', value: 23 }],
  [KeysCriticalValue.SuggestibilityBall]: [{ operator: '>', value: 14 }],
  [KeysCriticalValue.TotalBall]: [{ operator: '<', value: 60 }],
  [KeysCriticalValue.EthnicBall]: [{ operator: '<', value: 19 }],
  [KeysCriticalValue.SocialBall]: [{ operator: '<', value: 22 }],
  [KeysCriticalValue.PersonalityBall]: [{ operator: '<', value: 19 }],
  [KeysCriticalValue.SearchOfThrill]: [
    { operator: '<', value: 3.2 },
    { operator: '>', value: 6.3 },
  ],
  [KeysCriticalValue.DesireForDifficulties]: [
    { operator: '<', value: 3.2 },
    { operator: '>', value: 6.3 },
  ],
  [KeysCriticalValue.IntoleranceOfMonotony]: [
    { operator: '<', value: 3.2 },
    { operator: '>', value: 6.3 },
  ],
  [KeysCriticalValue.SearchOfNewExperiences]: [
    { operator: '<', value: 3.2 },
    { operator: '>', value: 6.3 },
  ],
  [KeysCriticalValue.OrganizationComp]: [{ operator: '<', value: 12 }],
  [KeysCriticalValue.SocioCulturalComp]: [{ operator: '<', value: 18 }],
  [KeysCriticalValue.SocioPracticalComp]: [{ operator: '<', value: 13 }],
  [KeysCriticalValue.SocioActivityComp]: [{ operator: '>', value: 28 }],
  [KeysCriticalValue.OrientationComp]: [{ operator: '<', value: 17 }],
};
